### PR TITLE
Add remaining kata, move specs into kata directories update README

### PR DESCRIPTION
**Pull request by ghost**
I think it would be a good idea to have the spec for each kata sitting in the same directory as the kata it's testing, just so we can keep everything connected to each kata (readme, solution, test, resources, etc) in one location.

### CODE REVIEW

**Comment by technancy** [comment]
Ok sounds good to me.

**Comment by technancy** [comment]
Although, what if we have 1 folder called specs, and 1 folder called katas ?   (and 1 called resources)

**Comment by ghost** [comment]
That would work as well. Hm, not sure which one I prefer now.

**Comment by technancy** [comment]
We should go the least folder route, and name the readme to kata-99-readme.md, incase we want to add beyond the 21 katas one day.

**Comment by ghost** [comment]
That does sound like a better idea. We could lay it out like:
- katas
  - pragprog
    - kata_1.rb
    - kata_2.rb
    - ...
- specs
  - pragprog
    - kata_1_spec.rb
    - kata_2_spec.rb
    - ...
- resources
  - pragprog
    - kata_4_resources
      - somefile.txt

If we namespace it with pragprog, then we'll be able to add other namespaces easily enough in the future.

**Comment by technancy** [comment]
Okay, I'll rearrange those now. :+1:

**Pull request merged**
